# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domain', '0001_initial'),
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='docs',
            field=models.ManyToManyField(related_name='domain_sector_docs', to='file.DocFile'),
        ),
    ]
