# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 17:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('file', '0001_initial'),
        ('domain', '0002_sector_docs'),
        ('link', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('saas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='links',
            field=models.ManyToManyField(related_name='domain_sector_links', to='link.DocLink'),
        ),
        migrations.AddField(
            model_name='sector',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domain_sector_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='domainregistration',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saas.Account'),
        ),
        migrations.AddField(
            model_name='domainregistration',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.Domain'),
        ),
        migrations.AddField(
            model_name='domain',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_domain_owned_by', to='saas.Account'),
        ),
        migrations.AddField(
            model_name='domain',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domain_domain_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='domain',
            name='docs',
            field=models.ManyToManyField(related_name='domain_domain_docs', to='file.DocFile'),
        ),
        migrations.AddField(
            model_name='domain',
            name='links',
            field=models.ManyToManyField(related_name='domain_domain_links', to='link.DocLink'),
        ),
        migrations.AddField(
            model_name='domain',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domain_domain_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='domain',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.Sector'),
        ),
    ]
