# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0001_initial'),
        ('entity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EntityGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='EntityGroupFamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saas.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'unit',
                'ordering': ('entity', 'name'),
            },
        ),
        migrations.AddField(
            model_name='entity',
            name='coordinates',
            field=jsonfield.fields.JSONField(blank=True, default={}),
        ),
        migrations.AddField(
            model_name='entity',
            name='info',
            field=jsonfield.fields.JSONField(blank=True, default={}),
        ),
        migrations.AddField(
            model_name='entity',
            name='ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refs', to='entity.Entity'),
        ),
        migrations.AddField(
            model_name='entity',
            name='ref_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entityspec',
            name='boolvalue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entityspec',
            name='flotvalue',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='entityspec',
            name='intvalue',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entityspec',
            name='spectype',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entityspec',
            name='textvalue',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='unit',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.Entity'),
        ),
        migrations.AddField(
            model_name='unit',
            name='ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.Unit'),
        ),
        migrations.AddField(
            model_name='entitygroup',
            name='entities',
            field=models.ManyToManyField(to='entity.Entity'),
        ),
        migrations.AddField(
            model_name='entitygroup',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.EntityGroupFamily'),
        ),
        migrations.AddField(
            model_name='activity',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.Entity'),
        ),
        migrations.AddField(
            model_name='activity',
            name='ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.Activity'),
        ),
        migrations.AddField(
            model_name='activity',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.Unit'),
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together=set([('entity', 'name')]),
        ),
    ]
