# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 09:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('saas', '0001_initial'),
        ('domain', '0003_auto_20151222_1750'),
        ('file', '0001_initial'),
        ('link', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared', models.BooleanField(default=False)),
                ('creation_timestamp', models.DateTimeField(blank=True)),
                ('modification_timestamp', models.DateTimeField(blank=True)),
                ('deprecated', models.BooleanField(default=False)),
                ('caption_todo', models.TextField()),
                ('caption_done', models.TextField()),
                ('danger_consequence', models.TextField()),
                ('comment', models.TextField(blank=True, default='')),
                ('is_periodic', models.BooleanField(default=False)),
                ('period_unit', models.CharField(choices=[('_', '_'), ('y', 'year'), ('m', 'month'), ('w', 'week'), ('d', 'day')], default='_', max_length=2)),
                ('period_value', models.PositiveIntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_action_owned_by', to='saas.Account')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_action_created_by', to=settings.AUTH_USER_MODEL)),
                ('docs', models.ManyToManyField(related_name='action_action_docs', to='file.DocFile')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.Domain')),
                ('links', models.ManyToManyField(related_name='action_action_links', to='link.DocLink')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_action_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared', models.BooleanField(default=False)),
                ('creation_timestamp', models.DateTimeField(blank=True)),
                ('modification_timestamp', models.DateTimeField(blank=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_actiontype_owned_by', to='saas.Account')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_actiontype_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_actiontype_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='action',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='action.ActionType'),
        ),
    ]
