# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 09:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hazard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('domain', '0003_auto_20151222_1750'),
        ('action', '0001_initial'),
        ('file', '0001_initial'),
        ('saas', '0001_initial'),
        ('link', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared', models.BooleanField(default=False)),
                ('creation_timestamp', models.DateTimeField(blank=True)),
                ('modification_timestamp', models.DateTimeField(blank=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('type', models.PositiveIntegerField(choices=[(1, 'by domains'), (2, 'by hazards'), (3, 'by hazards and actions')], default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_profile_owned_by', to='saas.Account')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProfileAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forced', models.BooleanField(default=False)),
                ('locked', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, default='')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='action.Action')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forced', models.BooleanField(default=False)),
                ('locked', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, default='')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.Domain')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileHazard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forced', models.BooleanField(default=False)),
                ('locked', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, default='')),
                ('hazard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hazard.Hazard')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.Profile')),
            ],
            options={
                'ordering': ['hazard'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='actions',
            field=models.ManyToManyField(through='profile.ProfileAction', to='action.Action'),
        ),
        migrations.AddField(
            model_name='profile',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_profile_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='docs',
            field=models.ManyToManyField(related_name='profile_profile_docs', to='file.DocFile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='domains',
            field=models.ManyToManyField(through='profile.ProfileDomain', to='domain.Domain'),
        ),
        migrations.AddField(
            model_name='profile',
            name='hazards',
            field=models.ManyToManyField(through='profile.ProfileHazard', to='hazard.Hazard'),
        ),
        migrations.AddField(
            model_name='profile',
            name='links',
            field=models.ManyToManyField(related_name='profile_profile_links', to='link.DocLink'),
        ),
        migrations.AddField(
            model_name='profile',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_profile_modified_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
