# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 17:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import z.doc.file.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('saas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared', models.BooleanField(default=False)),
                ('creation_timestamp', models.DateTimeField(blank=True)),
                ('modification_timestamp', models.DateTimeField(blank=True)),
                ('title', models.CharField(max_length=100)),
                ('doc', models.FileField(upload_to=z.doc.file.models.upload_docs_to)),
                ('description', models.TextField(blank=True, default='')),
                ('filetype', models.CharField(blank=True, default='', max_length=100)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_docfile_owned_by', to='saas.Account')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_docfile_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_docfile_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
