# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 09:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('action', '0001_initial'),
        ('hazard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entity', '0002_auto_20151231_0935'),
        ('assess', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='V1ActionTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(0, 'En place'), (1, 'A mener')], default=0)),
                ('responsible', models.CharField(blank=True, default='', max_length=100)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='action.Action')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='V1RiskAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(blank=True)),
                ('modification_timestamp', models.DateTimeField(blank=True)),
                ('comment', models.TextField(blank=True, default='')),
                ('frequency', models.PositiveIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')], default=0)),
                ('collective_protection', models.CharField(blank=True, choices=[('', '[non coté]'), ('A', 'A : Toutes les mesures sont prises'), ('B', 'B : Les mesures sont partiellement prises'), ('C', 'C : Les mesures ne sont pas vraiment prises'), ('D', "D : Aucune mesure n'est prise"), ('N', 'N :  Non applicable')], default='', max_length=2)),
                ('individual_protection', models.CharField(blank=True, choices=[('', '[non coté]'), ('A', 'A : Toutes les mesures sont prises'), ('B', 'B : Les mesures sont partiellement prises'), ('C', 'C : Les mesures ne sont pas vraiment prises'), ('D', "D : Aucune mesure n'est prise"), ('N', 'N :  Non applicable')], default='', max_length=2)),
                ('training', models.CharField(blank=True, choices=[('', '[non coté]'), ('A', 'A : Toutes les mesures sont prises'), ('B', 'B : Les mesures sont partiellement prises'), ('C', 'C : Les mesures ne sont pas vraiment prises'), ('D', "D : Aucune mesure n'est prise"), ('N', 'N :  Non applicable')], default='', max_length=2)),
                ('information', models.CharField(blank=True, choices=[('', '[non coté]'), ('A', 'A : Toutes les mesures sont prises'), ('B', 'B : Les mesures sont partiellement prises'), ('C', 'C : Les mesures ne sont pas vraiment prises'), ('D', "D : Aucune mesure n'est prise"), ('N', 'N :  Non applicable')], default='', max_length=2)),
                ('raw_score', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('weighted_score', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.Activity')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='v1_v1riskassessment_created_by', to=settings.AUTH_USER_MODEL)),
                ('hazard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hazard.Hazard')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='v1_v1riskassessment_modified_by', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assess.Session')),
            ],
            options={
                'ordering': ['hazard'],
            },
        ),
        migrations.CreateModel(
            name='V1RiskAssessmentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hazard_cause', models.TextField(blank=True, default='')),
                ('hazard_consequence', models.CharField(blank=True, default='', max_length=200)),
                ('hazard_level', models.PositiveIntegerField(default=1)),
                ('comment', models.TextField(blank=True, default='')),
                ('frequency', models.PositiveIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')], default=0)),
                ('collective_protection', models.CharField(blank=True, choices=[('', '[non coté]'), ('A', 'A : Toutes les mesures sont prises'), ('B', 'B : Les mesures sont partiellement prises'), ('C', 'C : Les mesures ne sont pas vraiment prises'), ('D', "D : Aucune mesure n'est prise"), ('N', 'N :  Non applicable')], default='', max_length=2)),
                ('individual_protection', models.CharField(blank=True, choices=[('', '[non coté]'), ('A', 'A : Toutes les mesures sont prises'), ('B', 'B : Les mesures sont partiellement prises'), ('C', 'C : Les mesures ne sont pas vraiment prises'), ('D', "D : Aucune mesure n'est prise"), ('N', 'N :  Non applicable')], default='', max_length=2)),
                ('training', models.CharField(blank=True, choices=[('', '[non coté]'), ('A', 'A : Toutes les mesures sont prises'), ('B', 'B : Les mesures sont partiellement prises'), ('C', 'C : Les mesures ne sont pas vraiment prises'), ('D', "D : Aucune mesure n'est prise"), ('N', 'N :  Non applicable')], default='', max_length=2)),
                ('information', models.CharField(blank=True, choices=[('', '[non coté]'), ('A', 'A : Toutes les mesures sont prises'), ('B', 'B : Les mesures sont partiellement prises'), ('C', 'C : Les mesures ne sont pas vraiment prises'), ('D', "D : Aucune mesure n'est prise"), ('N', 'N :  Non applicable')], default='', max_length=2)),
                ('raw_score', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('weighted_score', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.Activity')),
                ('assessment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='v1.V1RiskAssessment')),
                ('hazard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hazard.Hazard')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assess.Session')),
            ],
        ),
    ]
