# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idtag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idtag',
            name='label',
            field=models.CharField(default='GV1_ID', max_length=100),
        ),
    ]
