# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entity', '0002_auto_20151231_0935'),
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prevactivityext',
            name='activity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='entity.Activity'),
        ),
    ]
